// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace fb
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct heroconfigTB : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static heroconfigTB GetRootAsheroconfigTB(ByteBuffer _bb) { return GetRootAsheroconfigTB(_bb, new heroconfigTB()); }
  public static heroconfigTB GetRootAsheroconfigTB(ByteBuffer _bb, heroconfigTB obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public heroconfigTB __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public fb.heroconfigTR? HeroconfigTRS(int j) { int o = __p.__offset(4); return o != 0 ? (fb.heroconfigTR?)(new fb.heroconfigTR()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int HeroconfigTRSLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
  public fb.heroconfigTR? HeroconfigTRSByKey(int key) { int o = __p.__offset(4); return o != 0 ? fb.heroconfigTR.__lookup_by_key(__p.__vector(o), key, __p.bb) : null; }

  public static Offset<fb.heroconfigTB> CreateheroconfigTB(FlatBufferBuilder builder,
      VectorOffset heroconfigTRSOffset = default(VectorOffset)) {
    builder.StartTable(1);
    heroconfigTB.AddHeroconfigTRS(builder, heroconfigTRSOffset);
    return heroconfigTB.EndheroconfigTB(builder);
  }

  public static void StartheroconfigTB(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddHeroconfigTRS(FlatBufferBuilder builder, VectorOffset heroconfigTRSOffset) { builder.AddOffset(0, heroconfigTRSOffset.Value, 0); }
  public static VectorOffset CreateHeroconfigTRSVector(FlatBufferBuilder builder, Offset<fb.heroconfigTR>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateHeroconfigTRSVectorBlock(FlatBufferBuilder builder, Offset<fb.heroconfigTR>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartHeroconfigTRSVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<fb.heroconfigTB> EndheroconfigTB(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<fb.heroconfigTB>(o);
  }
  public static void FinishheroconfigTBBuffer(FlatBufferBuilder builder, Offset<fb.heroconfigTB> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedheroconfigTBBuffer(FlatBufferBuilder builder, Offset<fb.heroconfigTB> offset) { builder.FinishSizePrefixed(offset.Value); }
};

public struct heroconfigTR : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static heroconfigTR GetRootAsheroconfigTR(ByteBuffer _bb) { return GetRootAsheroconfigTR(_bb, new heroconfigTR()); }
  public static heroconfigTR GetRootAsheroconfigTR(ByteBuffer _bb, heroconfigTR obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public heroconfigTR __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int _id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public float _baseatk { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float _sp { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float _hp { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float _attackdistance { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float _attackinterval { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

  public static Offset<fb.heroconfigTR> CreateheroconfigTR(FlatBufferBuilder builder,
      int _id = 0,
      float _baseatk = 0.0f,
      float _sp = 0.0f,
      float _hp = 0.0f,
      float _attackdistance = 0.0f,
      float _attackinterval = 0.0f) {
    builder.StartTable(6);
    heroconfigTR.Add_attackinterval(builder, _attackinterval);
    heroconfigTR.Add_attackdistance(builder, _attackdistance);
    heroconfigTR.Add_hp(builder, _hp);
    heroconfigTR.Add_sp(builder, _sp);
    heroconfigTR.Add_baseatk(builder, _baseatk);
    heroconfigTR.Add_id(builder, _id);
    return heroconfigTR.EndheroconfigTR(builder);
  }

  public static void StartheroconfigTR(FlatBufferBuilder builder) { builder.StartTable(6); }
  public static void Add_id(FlatBufferBuilder builder, int Id) { builder.AddInt(0, Id, 0); }
  public static void Add_baseatk(FlatBufferBuilder builder, float Baseatk) { builder.AddFloat(1, Baseatk, 0.0f); }
  public static void Add_sp(FlatBufferBuilder builder, float Sp) { builder.AddFloat(2, Sp, 0.0f); }
  public static void Add_hp(FlatBufferBuilder builder, float Hp) { builder.AddFloat(3, Hp, 0.0f); }
  public static void Add_attackdistance(FlatBufferBuilder builder, float Attackdistance) { builder.AddFloat(4, Attackdistance, 0.0f); }
  public static void Add_attackinterval(FlatBufferBuilder builder, float Attackinterval) { builder.AddFloat(5, Attackinterval, 0.0f); }
  public static Offset<fb.heroconfigTR> EndheroconfigTR(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<fb.heroconfigTR>(o);
  }

  public static VectorOffset CreateSortedVectorOfheroconfigTR(FlatBufferBuilder builder, Offset<heroconfigTR>[] offsets) {
    Array.Sort(offsets, (Offset<heroconfigTR> o1, Offset<heroconfigTR> o2) => builder.DataBuffer.GetInt(Table.__offset(4, o1.Value, builder.DataBuffer)).CompareTo(builder.DataBuffer.GetInt(Table.__offset(4, o2.Value, builder.DataBuffer))));
    return builder.CreateVectorOfTables(offsets);
  }

  public static heroconfigTR? __lookup_by_key(int vectorLocation, int key, ByteBuffer bb) {
    int span = bb.GetInt(vectorLocation - 4);
    int start = 0;
    while (span != 0) {
      int middle = span / 2;
      int tableOffset = Table.__indirect(vectorLocation + 4 * (start + middle), bb);
      int comp = bb.GetInt(Table.__offset(4, bb.Length - tableOffset, bb)).CompareTo(key);
      if (comp > 0) {
        span = middle;
      } else if (comp < 0) {
        middle++;
        start += middle;
        span -= middle;
      } else {
        return new heroconfigTR().__assign(tableOffset, bb);
      }
    }
    return null;
  }
};


}
